In [1]:
import numpy as np

In [2]:
I3 = np.identity(3,dtype='int32')

In [3]:
I3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
print(I3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
np.repeat(I3,5,axis=0)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [6]:
O3 = np.zeros((3,3),dtype='int32')

In [7]:
O3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
#matrix multiplication

In [10]:
np.matmul(I3,I3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.linalg.det(I3) #determinant

1.0

In [16]:
v1 = np.array([1,2,3])
v2 = np.array([5,6,7])
np.vstack([v1,v2,v1])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3]])

In [17]:
np.hstack([v1,v2,v1])

array([1, 2, 3, 5, 6, 7, 1, 2, 3])

In [19]:
a = np.ones((3,5))

In [20]:
b = np.zeros((3,9))

In [21]:
np.hstack([a,b])

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])